import type { ValidAmUploadCase } from './am-valid-upload';

export const VALID_AM_UPLOAD_CASES: Record<string, ValidAmUploadCase> = {
  'E4-AM-01.1': {
    caseId: 'E4-AM-01.1',
    section: 'Parametrización',
    view: 'Cuentas Contables',
    entityName: 'Cuentas Contables',
    fileName: 'REAL Cuentas Contables AM.xlsx',
    modalTitle: /Cargar Cuentas Contables/i,
  },
  'E4-AM-01.1.1': {
    caseId: 'E4-AM-01.1.1',
    section: 'Parametrización',
    view: 'Cuentas Contables',
    entityName: 'Cuentas Contables',
    fileName: 'REAL Cuentas Contables AM.xlsx',
    modalTitle: /Cargar Cuentas Contables/i,
    validateReplaceFile: true,
  },
  'E4-AM-01.2': {
    caseId: 'E4-AM-01.2',
    section: 'Parametrización',
    view: 'Partidas',
    entityName: 'Partidas',
    fileName: 'REAL Partidas AM.xlsx',
    modalTitle: /Cargar Partidas/i,
  },
  'E4-AM-01.2.1': {
    caseId: 'E4-AM-01.2.1',
    section: 'Parametrización',
    view: 'Partidas',
    entityName: 'Partidas',
    fileName: 'REAL Partidas AM.xlsx',
    modalTitle: /Cargar Partidas/i,
    validateReplaceFile: true,
  },
  'E4-AM-01.3': {
    caseId: 'E4-AM-01.3',
    section: 'Parametrización',
    view: 'Centros',
    entityName: 'Centros',
    fileName: 'REAL Centros AM.xlsx',
    modalTitle: /Cargar Centros/i,
  },
  'E4-AM-01.3.1': {
    caseId: 'E4-AM-01.3.1',
    section: 'Parametrización',
    view: 'Centros',
    entityName: 'Centros',
    fileName: 'REAL Centros AM.xlsx',
    modalTitle: /Cargar Centros/i,
    validateReplaceFile: true,
  },
  'E4-AM-02.1': {
    caseId: 'E4-AM-02.1',
    section: 'Aprovisionamiento',
    view: 'Exactus',
    entityName: 'Exactus sin Procesar',
    fileName: 'REAL Exactus sin Procesar AM.xlsx',
    modalTitle: /Cargar Exactus/i,
  },
  'E4-AM-02.1.1': {
    caseId: 'E4-AM-02.1.1',
    section: 'Aprovisionamiento',
    view: 'Exactus',
    entityName: 'Exactus sin Procesar',
    fileName: 'REAL Exactus sin Procesar AM.xlsx',
    modalTitle: /Cargar Exactus/i,
    validateReplaceFile: true,
    catalogIssue:
      'TODO [CATALOGO]: titulo y datos indican Exactus sin Procesar, pero los pasos 2 y 4 indican Centros. Se requiere correccion funcional.',
  },
  'E4-AM-02.2': {
    caseId: 'E4-AM-02.2',
    section: 'Aprovisionamiento',
    view: 'Exactus procesado',
    entityName: 'Exactus procesado',
    fileName: 'REAL Exactus procesado AM.xlsx',
    modalTitle: /Cargar Exactus procesado/i,
  },
  'E4-AM-02.3': {
    caseId: 'E4-AM-02.3',
    section: 'Aprovisionamiento',
    view: 'Unidad de Cuenta AM',
    entityName: 'Unidad de Cuenta AM',
    fileName: 'REAL Unidad de Cuenta AM.xlsx',
    modalTitle: /Cargar Unidad de Cuenta AM/i,
  },
  'E4-AM-02.3.1': {
    caseId: 'E4-AM-02.3.1',
    section: 'Aprovisionamiento',
    view: 'Unidad de Cuenta AM',
    entityName: 'Unidad de Cuenta AM',
    fileName: 'REAL Unidad de Cuenta AM.xlsx',
    modalTitle: /Cargar Unidad de Cuenta AM/i,
    validateReplaceFile: true,
  },
};
