import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://distribuciongastosdev.pacificotest.com.pe/login/?redirect=%2Fdistribuciones%2F');
  await page.locator('div').nth(3).click();
  await page.getByRole('button', { name: 'Logo de Microsoft Iniciar' }).click();
  await page.goto('https://login.microsoftonline.com/e6141c14-330a-4ac4-a1a9-402caa66e219/oauth2/v2.0/authorize?client_id=e88bdcac-fa26-40bc-857f-8cc07c6e95eb&scope=api%3A%2F%2FMotorDistribucionGastos%2FAPI.ReadWrite.All%20openid%20profile%20offline_access&redirect_uri=https%3A%2F%2Fdistribuciongastosdev.pacificotest.com.pe%2F&client-request-id=019d25dc-2ddf-70b7-9dfa-f51be03c14d0&response_mode=fragment&client_info=1&nonce=019d25dc-2de1-767d-9bbf-46561bbabb6f&state=eyJpZCI6IjAxOWQyNWRjLTJkZTEtNzgyMy04NTNlLTIwZjExZTMyZTliMCIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D&x-client-SKU=msal.js.browser&x-client-VER=4.28.1&response_type=code&code_challenge=Z3nSLjiqwpBbZ3QhrIlu050Y3QCPp7JvZwEOsdWlqmg&code_challenge_method=S256&sso_reload=true');
  await page.getByRole('textbox', { name: 'Enter your email, phone, or' }).click();
  await page.getByRole('textbox', { name: 'Enter your email, phone, or' }).fill('psilvestre@pacificotest.com.pe');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Enter the password for' }).click();
  await page.getByRole('textbox', { name: 'Enter the password for' }).fill('MDG rocks!');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Asientos Manuales', exact: true }).click();
  await page.locator('html').click();
  await page.getByRole('button', { name: 'Asientos Manuales', exact: true }).click();
  await page.locator('html').click();
  await page.getByRole('button', { name: 'Procesos' }).click();
  await page.getByRole('button', { name: 'Asientos Manuales', exact: true }).click();
  await page.locator('html').click();
  await page.getByRole('button', { name: '202508_REAL_Flujo_Mes REAL' }).click();
  await page.getByLabel('202508_REAL_Flujo_MesREAL').getByText('REAL', { exact: true }).click();
  await page.getByRole('button', { name: 'Asientos Manuales', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Gastos Financieros' }).click();
  await page.getByRole('button', { name: 'Procesos' }).click();
  await page.getByRole('button', { name: 'Procesos' }).click();
  await page.getByRole('link', { name: 'Procesos' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('202506');
  await page.getByRole('combobox').click();
  await page.getByText('Resumido').click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(1).click();
  await page.getByRole('checkbox', { name: 'Exactus' }).click();
  await page.getByRole('checkbox', { name: 'AMED' }).click();
  await page.getByRole('checkbox', { name: 'AP Vida' }).click();
  await page.getByRole('textbox').nth(1).click();
  await page.locator('circle').nth(1).click();
  await page.locator('div:nth-child(2) > .relative > .lucide').click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('1');
  await page.getByRole('main').locator('div').filter({ hasText: /^Procesos$/ }).click();
  await page.getByText('FASE 3').click();
  await page.getByText('FASE 3').click();
  await page.getByText('Distribuir Objetos de Costo a').click();
  await page.getByRole('button', { name: 'Ejecutar Todo' }).click();
  await page.getByRole('button', { name: 'No' }).click();
});