import type { IncidentCandidate, IncidentRuntimeConfig } from '../incident.types';

export function makeProviderTestConfig(provider: IncidentRuntimeConfig['provider']): IncidentRuntimeConfig {
  return {
    autoCreateIncidents: true,
    mode: 'create',
    provider,
    attachEvidence: false,
    attachVideo: false,
    maxVideoMb: 50,
    requestTimeoutMs: 15_000,
    azureOrganization: 'org',
    azureProject: 'project',
    hasAzurePat: true,
    azureValidateOnly: false,
    azureAttachEvidence: false,
    azureAttachVideo: false,
    azureMaxVideoMb: 50,
    jiraBaseUrl: 'https://jira.example.test',
    jiraProjectKey: 'QA',
    jiraEmail: 'qa@example.test',
    hasJiraApiToken: true,
    jiraIssueType: 'Bug',
    jiraValidateOnly: true,
    trelloBoardId: 'board-1',
    trelloListId: 'list-1',
    hasTrelloApiKey: true,
    hasTrelloToken: true,
    trelloValidateOnly: true,
  };
}

export function makeProviderTestCandidate(): IncidentCandidate {
  return {
    caseId: 'E37-AM-01.01.1',
    title: 'elimina registro',
    bugTitle: '[QA-AUTO][E37-AM-01.01.1] No se encuentra Eliminar',
    bugDescription: 'N/D',
    block: 'Bloque 5',
    specFile: 'tests/e2e/bloque-5/E37-AM-01.01.1/E37-AM-01.01.1.spec.ts',
    project: 'chromium-gestorAM',
    role: 'gestorAM',
    browser: 'chromium',
    status: 'FAILED',
    durationMs: 1000,
    retry: 0,
    finalUrl: 'https://example.test',
    phase: 'Eliminar',
    classification: 'NAV_FAILURE',
    errorMessage: 'Debe existir Eliminar',
    expectedResult: 'Eliminar visible',
    observedResult: 'Eliminar no visible',
    stackSummary: 'file.ts:1',
    expected: 'visible',
    received: 'N/D',
    errorOrigin: 'file.ts:1',
    timeout: '5000 ms',
    executedAt: '2026-08-20T00:00:00.000Z',
    evidence: { screenshot: [], video: [], trace: [], htmlReport: [], logs: [] },
    action: 'CANDIDATO A BUG',
    technicalDiagnostic: {
      error: 'ELEMENT_NOT_FOUND',
      caseId: 'E37-AM-01.01.1',
      phase: 'Eliminar',
      probableCause: 'OPTION_NOT_AVAILABLE',
      message: 'Debe existir Eliminar',
      expectedRole: 'gestorAM',
      expectedProject: 'chromium-gestorAM',
      usedProject: 'chromium-gestorAM',
      file: 'file.ts',
      technicalOrigin: 'file.ts:1',
      view: 'Cuentas Contables',
    },
    incidentDecision: {
      classification: 'BUSINESS_RULE_FAILURE',
      probableCause: 'OPTION_NOT_AVAILABLE',
      confidence: 'HIGH',
      evidence: [],
      decision: 'BUG_AUTO',
      reason: 'Accion no disponible.',
      recommendation: 'Registrar incidencia.',
      azureDevOpsEligibility: 'ELEGIBLE PARA CREACION AUTOMATICA',
    },
    originalError: 'Error: Debe existir Eliminar',
  };
}
